Add patch transaction method
slykio/slyk-sdk-node pull request #48
Opened 2021-09-24 13:01 UTC by nunovieira220

This PR aims to add patch transaction method on the respective module.

2021-09-24 14:32 UTC, kratos-42 requested changes

2021-09-24 14:32 UTC, kratos-42 commented on src/transaction/managers/transaction-manager.js
> +  /**
Fix identation.

2021-09-24 14:32 UTC, kratos-42 commented on src/transaction/models/transaction-model.js
> +  patch(data) {
Add a test for this method.

2021-09-24 14:58 UTC, kratos-42 approved these changes

2021-09-29 11:46 UTC, johnmaia approved these changes

2021-09-29 15:25 UTC, merged